name: Build watchOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the project
        run: |
          xcodebuild -project "watch/Complete/CreatingAwatchOSApp.xcodeproj" \
          -scheme "CreatingAwatchOSApp" \
          -sdk iphoneos \
          -configuration Release \
          clean build

      - name: Archive the app
        run: |
          xcodebuild -project "watch/Complete/CreatingAwatchOSApp.xcodeproj" \
          -scheme "CreatingAwatchOSApp" \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/YourApp.xcarchive \
          archive

      - name: Export the app as IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/YourApp.xcarchive \
          -exportPath $PWD/build \
          -exportOptionsPlist "ExportOptions.plist"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourApp
          path: build/YourApp.ipa
