name: Build watchOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode and install certificates
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > apple_cert.p12
          security create-keychain -p "" build.keychain
          security import apple_cert.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" ~/Library/Keychains/build.keychain
          security list-keychains
          security show-keychain-info ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain

      - name: Check certificate details
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > apple_cert.p12
          ls -l apple_cert.p12
          hexdump -C apple_cert.p12 | head -n 10          

      - name: Install provisioning profile for main app
        run: |
          echo "${{ secrets.APPLE_PROVISIONING_PROFILE }}" | base64 --decode > main_profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv main_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install provisioning profile for watch app
        run: |
          echo "${{ secrets.APPLE_WATCH_PROVISIONING_PROFILE }}" | base64 --decode > watch_profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv watch_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/


      # Build the watchOS app for physical device
      - name: Build the watchOS app for device
        run: |
          xcodebuild -project "Complete/CreatingAwatchOSApp.xcodeproj" \
          -scheme "WatchLandmarks Watch App" \
          -sdk watchos \
          -destination 'generic/platform=watchOS' \
          -configuration Release \
          -allowProvisioningUpdates \
          DEVELOPMENT_TEAM=${{ secrets.APPLE_DEVELOPMENT_TEAM }} \
          clean build

      - name: Archive the app
        run: |
          xcodebuild -project "Complete/CreatingAwatchOSApp.xcodeproj" \
          -scheme "WatchLandmarks Watch App" \
          -sdk watchos \
          -configuration Release \
          -archivePath $PWD/build/WatchLandmarks.xcarchive \
          archive

      - name: Export the app as IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/WatchLandmarks.xcarchive \
          -exportPath $PWD/build \
          -exportOptionsPlist "Complete/CreatingAwatchOSApp/ExportOptions.plist"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WatchLandmarks
          path: build/WatchLandmarks.ipa
