name: Build watchOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode and install certificates
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > apple_cert.p12
          security create-keychain -p "" build.keychain
          security import apple_cert.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain

      - name: Install provisioning profile
        run: |
          echo "${{ secrets.APPLE_PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build the watchOS app
        run: |
          xcodebuild -project "Complete/CreatingAwatchOSApp.xcodeproj" \
          -scheme "WatchLandmarks Watch App" \
          -sdk watchos \
          -destination 'platform=watchOS Simulator,name=Apple Watch Series 6 - 40mm' \
          -configuration Release \
          clean build

      - name: Archive the app
        run: |
          xcodebuild -project "Complete/CreatingAwatchOSApp.xcodeproj" \
          -scheme "WatchLandmarks Watch App" \
          -sdk watchos \
          -configuration Release \
          -archivePath $PWD/build/WatchLandmarks.xcarchive \
          archive

      - name: Export the app as IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/WatchLandmarks.xcarchive \
          -exportPath $PWD/build \
          -exportOptionsPlist "Complete/CreatingAwatchOSApp.xcodeproj/ExportOptions.plist"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WatchLandmarks
          path: build/WatchLandmarks.ipa
